In [45]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt 
import os

In [46]:
for dirname  ,_, filenames in os.walk('c:/Users/Sandeep/Downloads/'):
    for filename in filenames :
        if filename.endswith('csv'):
            print(os.path.join(dirname,filename))

c:/Users/Sandeep/Downloads/Book 2(Sheet1).csv
c:/Users/Sandeep/Downloads/customer_profiles.csv
c:/Users/Sandeep/Downloads/customer_support_tickets.csv
c:/Users/Sandeep/Downloads/ecommerce_data_science_practice.csv
c:/Users/Sandeep/Downloads/marketing_campaigns (1).csv
c:/Users/Sandeep/Downloads/marketing_campaigns.csv
c:/Users/Sandeep/Downloads/product_details.csv
c:/Users/Sandeep/Downloads/rootkey (2).csv
c:/Users/Sandeep/Downloads/zomato.csv\zomato.csv

In [47]:
df = pd.read_csv('c:/Users/Sandeep/Downloads\ecommerce_data_science_practice.csv')
df.head(2)

<>:1: SyntaxWarning: invalid escape sequence '\e'
<>:1: SyntaxWarning: invalid escape sequence '\e'
C:\Users\Sandeep\AppData\Local\Temp\ipykernel_3388\3252684121.py:1: SyntaxWarning: invalid escape sequence '\e'
  df = pd.read_csv('c:/Users/Sandeep/Downloads\ecommerce_data_science_practice.csv')

,daTransaction_ID,Timestamp,User_ID,City,Product_Category,Price_Per_Unit,Quantity,Payment_Method,Coupon_Applied,Total_Amount,Is_Repeat_Customer
0,TXN_100000,2026-04-13 19:28:00,USR_5815,Delhi,Electronics,11656.0,2,Cash on Delivery,1,23312.0,0
1,TXN_100001,2026-01-15 10:07:00,USR_5442,Hyderabad,Home Appliances,24118.0,1,Debit Card,0,24118.0,1

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   daTransaction_ID    2500 non-null   object
 1   Timestamp           2500 non-null   object
 2   User_ID             2500 non-null   object
 3   City                2460 non-null   object
 4   Product_Category    2500 non-null   object
 5   Price_Per_Unit      2441 non-null   float64
 6   Quantity            2500 non-null   int64
 7   Payment_Method      2465 non-null   object
 8   Coupon_Applied      2500 non-null   int64
 9   Total_Amount        2441 non-null   float64
 10  Is_Repeat_Customer  2500 non-null   int64
dtypes: float64(2), int64(3), object(6)
memory usage: 215.0+ KB

In [49]:
df.isnull().sum()

daTransaction_ID       0
Timestamp              0
User_ID                0
City                  40
Product_Category       0
Price_Per_Unit        59
Quantity               0
Payment_Method        35
Coupon_Applied         0
Total_Amount          59
Is_Repeat_Customer     0
dtype: int64

In [50]:
df.shape

(2500, 11)

In [51]:
df.drop_duplicates(inplace=True)
df_df = df['Price_Per_Unit'].median()
df['Price_Per_Unit'] = df['Price_Per_Unit'].fillna(df_df)
df['Total_Amount'] = df['Price_Per_Unit'] * df['Quantity']
df = df.fillna({'City':'unknown City', 'Payment_Method' : 'unknown Payment_Method'})
df.isnull().sum()

daTransaction_ID      0
Timestamp             0
User_ID               0
City                  0
Product_Category      0
Price_Per_Unit        0
Quantity              0
Payment_Method        0
Coupon_Applied        0
Total_Amount          0
Is_Repeat_Customer    0
dtype: int64

In [54]:
df = df.apply(lambda x: x.astype(str).str.lower().str.strip().str.replace(' ','_') if x.dtype == 'object' else x)
df.columns = df.columns.str.lower().str.strip().str.replace(' ','_')
df.head()

,datransaction_id,timestamp,user_id,city,product_category,price_per_unit,quantity,payment_method,coupon_applied,total_amount,is_repeat_customer
0,txn_100000,2026-04-13_19:28:00,usr_5815,delhi,electronics,11656.0,2,cash_on_delivery,1,23312.0,0
1,txn_100001,2026-01-15_10:07:00,usr_5442,hyderabad,home_appliances,24118.0,1,debit_card,0,24118.0,1
2,txn_100002,2026-01-21_06:57:00,usr_5142,bangalore,books,200.0,1,upi,0,200.0,0
3,txn_100003,2026-03-16_10:23:00,usr_5191,delhi,electronics,29872.0,3,upi,0,89616.0,0
4,txn_100004,2026-04-27_03:39:00,usr_6410,delhi,clothing,1938.0,1,cash_on_delivery,1,1938.0,0

In [59]:
df.shape

(2500, 11)

In [56]:
for i , run in enumerate(df['city'].unique(),start=1):
    print(i ,run)

1 delhi
2 hyderabad
3 bangalore
4 mumbai
5 kolkata
6 ahmedabad
7 pune
8 chennai
9 unknown_city

In [58]:
for city1 in df['city'].unique():
    rows , cols =  df[df['city'] == city1].shape
    print(f'{city1} rows {rows} , column {cols}')

delhi rows 489 , column 11
hyderabad rows 304 , column 11
bangalore rows 358 , column 11
mumbai rows 596 , column 11
kolkata rows 131 , column 11
ahmedabad rows 109 , column 11
pune rows 269 , column 11
chennai rows 204 , column 11
unknown_city rows 40 , column 11